recipe: default.v1

language: de

pipeline:
- name: SpacyNLP
  model: de_core_news_md
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 250
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.87
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
  max_history: 5
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: action_custom_fallback
  enable_fallback_prediction: true
- name: TEDPolicy
  max_history: 10
  epochs: 150
  constrain_similarities: true
assistant_id: 20230403-141959-complex-infrastructure
