name: ci

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'rasa/*'
      - '**.yml'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'rasa/*'
      - '**.yml'
      - 'Dockerfile'

jobs:
  train_test:
    name: "Train and test model"
    runs-on: ubuntu-latest
    if: github.ref_type != 'tag'
    steps:
      # Checks-out GitHub repository
      # more: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - run: pip install -r requirements.txt

      - run: python -m spacy download de_core_news_md

      - run: rasa train --domain domain
        working-directory: ./rasa

      - run: rasa test --domain domain
        working-directory: ./rasa

  train_test_upload:
    name: "Train, test and upload model"
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      # Checks-out GitHub repository
      # more: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - run: pip install -r requirements.txt

      - run: python -m spacy download de_core_news_md

      - run: rasa train --domain domain
        working-directory: ./rasa

      - run: rasa test --domain domain
        working-directory: ./rasa

      # The 'actions/upload-artifact' action to upload files
      # More: https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v3
        with:
          name: rasa-cfg
          path: |
            rasa/results

      - uses: actions/upload-artifact@v3
        with:
          name: rasa-model
          path: rasa/models

  docker:
    name: "Docker build and push to Amazon ECR"
    runs-on: ubuntu-latest
    needs: train_test_upload
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - uses: actions/download-artifact@v3
        with:
          name: rasa-model
          path: rasa/models

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 312310136925.dkr.ecr.eu-central-1.amazonaws.com/climatechangebot
          ECR_REPOSITORY: chatbot
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GIT_TAG_NAME .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GIT_TAG_NAME


